project:
  type: website
  resources:
    - exercises.zip

website:
  page-navigation: true
  title: "Reproducible Documents, Websites, and Books with Quarto"
  description: "SDSS 2023 workshops on Quarto"
  favicon: "images/logo.png"

  repo-url: https://github.com/mine-cetinkaya-rundel/quarto-sdss
  repo-actions: [edit, issue]

  open-graph: true
  twitter-card:
    creator: "@minebocek"
    image: "images/twitter-card.png"

  sidebar:
    background: "#CCD951"
    logo: "images/logo.png"
    pinned: true
    align: center
    tools:
      - icon: github
        href: https://github.com/mine-cetinkaya-rundel/quarto-sdss
        text: "GitHub organization"
      - icon: code-square
        href: https://posit.cloud
        text: "Posit Cloud"

    style: docked
    search: true
    collapse-level: 2
    contents:
      - href: index.qmd
        text: Home
      - href: pre-work.qmd
        text: Pre-work
      - section: "Producing a Single Document"
        contents:
          - href: 1-1-hello-quarto/index.qmd
            text: Hello Quarto
          - href: 1-2-documents/index.qmd
            text: Documents
          - href: 1-3-presentations/index.qmd
            text: Presentations
          - href: 1-4-articles/index.qmd
            text: Articles + Wrap-up
      - section: "Producing Websites and Books"
        contents:
          - href: 2-1-websites/index.qmd
            text: Websites
          - href: 2-2-books/index.qmd
            text: Books
          - href: 2-3-projects/index.qmd
            text: Projects
          - href: 2-4-wrap-up/index.qmd
            text: Wrap-up

  page-footer:
    right: "This page is built with 💚 and [Quarto](https://quarto.org/)."
    left: "&copy; Copyright 2023, Mine Çetinkaya-Rundel"
    background: "#CCD951"

format:
  html:
    theme:
      light: [cosmo, style/quarto-sdss.scss]
      dark: [cosmo, style/quarto-sdss.scss, style/dark.scss]
    toc: true
    code-copy: true
    code-overflow: wrap
    mainfont: "Atkinson Hyperlegible"

execute:
  freeze: auto

editor: visual
